IgnoreURLs:
  - ^/forum$
  - ^/zoom/dev/$
  - ^/dev-meeting$
  - ^/calendar/$
  - ^/find-issue/$
  - ^/board/
  - ^/roadmap
  - ^/src
  - ^/examples
  - ^/forum
  - ^/docker-mixin/src
IgnoreAltMissing: true
IgnoreInternalEmptyHash: true