name: porter/test-porter-release
on:
  pull_request:
    branches:
      - main
env:
  PORTER_PACKAGES_REMOTE: https://github.com/carolynvs/porter-packages.git
  PORTER_RELEASE_REPOSITORY: github.com/carolynvs/porter
jobs:
  build_pipelinesrelease_template:
    name: build_pipelinesrelease_template
    uses: './.github/workflows/build_pipelinesrelease_template.yml'
    with:
      registry: ghcr.io/getporter/test
      shouldPublish: true
      skipTests: true
